AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::286387522442:role/sed_role'
      Environment:
        Variables:
          TARGET_BUCKET: gl-inter-store
      Layers:
        - 'arn:aws:lambda:us-east-1:286387522442:layer:pypdf-layer:1'
        - 'arn:aws:lambda:us-east-1:286387522442:layer:aws_auth_layer:1'
